import { StringDate } from 'src/core/domain/vo/StringDate';
import { Amount } from '../../../wallets/domain/vo/Amount';
import { TransactionType } from '../vo/TransactionType';
import { Category } from './Category';
import { SubCategory } from './SubCategory';
import { InvalidTransferTransaction } from '../exceptions/TransactionException';

export const TransferTransaction = new TransactionType('transfer');
export const IncomeTransaction = new TransactionType('income');
export const ExpenseTransaction = new TransactionType('expense');

export class Transaction {
  constructor(
    private readonly id: number,
    private readonly walletId: number,
    private readonly amount: Amount,
    private readonly concept: string,
    private readonly type: TransactionType,
    private readonly date: StringDate,
    private readonly categoryId: number,
    private readonly subCategoryId: number,
    private readonly destinationWalletId: number | null = null,
    private readonly category: Category | null = null,
    private readonly subCategory: SubCategory | null = null,
  ) {
    this.validateBusinessRules();
  }

  static forCreate(
    walletId: number,
    amount: Amount,
    concept: string,
    type: TransactionType,
    date: StringDate,
    categoryId: number,
    subCategoryId: number,
    destinationWalletId?: number | null,
  ) {
    return new Transaction(
      0, // ID will be generated by the database
      walletId,
      amount,
      concept,
      type,
      date,
      categoryId,
      subCategoryId,
      destinationWalletId,
    );
  }

  createDestinationTransaction() {
    if (this._type.equals(TransferTransaction) && this._destinationWalletId) {
      return new Transaction(
        0,
        this._destinationWalletId,
        this._amount,
        this._concept,
        this._type,
        this._date,
        this._categoryId,
        this._subCategoryId,
        this._destinationWalletId,
      );
    }

    throw new InvalidTransferTransaction();
  }

  addCategories(category: Category, subCategory: SubCategory) {
    return new Transaction(
      this._id, // ID will be generated by the database
      this._walletId,
      this._amount,
      this._concept,
      this._type,
      this._date,
      this._categoryId,
      this._subCategoryId,
      this._destinationWalletId,
      category,
      subCategory,
    );
  }

  validateBusinessRules() {
    // Rule: Transfers transaction must have a destination
    if (this.type.isTransfer && !this.destinationWalletId) {
      throw new Error(
        'Destination wallet ID is required for transfer transactions',
      );
    }

    // Rule: Amounts must always be positive
    if (this.amount.getValue() <= 0) {
      throw new Error('Transaction amount must be a positive value.');
    }
  }

  get _id() {
    return this.id;
  }

  get _walletId() {
    return this.walletId;
  }

  get _destinationWalletId() {
    return this.destinationWalletId;
  }

  get _categoryId() {
    return this.categoryId;
  }

  get _subCategoryId() {
    return this.subCategoryId;
  }

  get _category() {
    return this.category;
  }

  get _subCategory() {
    return this.subCategory;
  }

  get _amount() {
    return this.amount;
  }

  get _concept() {
    return this.concept;
  }

  get _type() {
    return this.type;
  }

  get _date() {
    return this.date;
  }
}
