import type { Category } from "./Category";
import type { SubCategory } from "./SubCategory";
import type { Amount } from "@core/domain/vo/Amount";
import { TransactionType } from "../vo/TransactionType";
import type { StringDate } from "@core/domain/vo/StringDate";

export const IncomeTransaction = new TransactionType("income");
export const ExpenseTransaction = new TransactionType("expense");
export const TransferTransaction = new TransactionType("transfer");

export class Transaction {
  constructor(
    private readonly id: number,
    private readonly walletId: number,
    private readonly amount: Amount,
    private readonly concept: string,
    private readonly date: StringDate,
    private readonly type: TransactionType,
    private readonly category: Category | null = null,
    private readonly subCategory: SubCategory | null = null,
    private readonly destinationWalletId: number | null = null,
  ) {
    this.validateBusinessRules();
  }

  static forCreate(
    walletId: number,
    amount: Amount,
    concept: string,
    date: StringDate,
    type: TransactionType,
    category: Category | null = null,
    subCategory: SubCategory | null = null,
    destinationWalletId?: number | null,
  ) {
    return new Transaction(
      0, // ID will be generated by the database
      walletId,
      amount,
      concept,
      date,
      type,
      category,
      subCategory,
      destinationWalletId,
    );
  }

  validateBusinessRules() {
    // Rule: Transfers transaction must have a destination
    if (this.type.isTransfer && !this.destinationWalletId) {
      throw new Error(
        "Destination wallet ID is required for transfer transactions",
      );
    }

    // Rule: Amounts must always be positive
    if (this.amount.getValue() <= 0) {
      throw new Error("Transaction amount must be a positive value.");
    }
  }

  get _id() {
    return this.id;
  }

  get _walletId() {
    return this.walletId;
  }

  get _destinationWalletId() {
    return this.destinationWalletId;
  }

  get _category() {
    return this.category;
  }

  get _subCategory() {
    return this.subCategory;
  }

  get _date() {
    return this.date;
  }

  get _amount() {
    return this.amount;
  }

  get _concept() {
    return this.concept;
  }

  get _type() {
    return this.type;
  }
}
